FROM node:16.16.0-alpine AS client
EXPOSE 4200 49153
# USER node

RUN mkdir /home/node/.npm-global
ENV PATH=/home/node/.npm-global/bin:$PATH
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

RUN npm install --location=global @angular/cli@14.2.7

WORKDIR /src
COPY ./src/KiteHelper/ClientApp/ .

RUN npm install

CMD ["ng", "serve", "--port", "4200", "--host", "0.0.0.0", "--disable-host-check", "--poll", "2000"]