site_name: KiteConnect .Net Docs
nav:
    - Introduction: index.md
    - Quickstart: quickstart.md
    - Reference: reference.md
    - Changelog: changelog.md
    - License: license.md
theme: 
  palette:
    primary: 'white'
    accent: 'red'
  name: 'material'
  logo: 'assets/logo.svg'
  favicon: 'assets/favicon.png'

repo_name: 'zerodhatech/dotnetkiteconnect'
repo_url: 'https://github.com/zerodhatech/dotnetkiteconnect'

copyright: 'Copyright &copy; 2019 Zerodha Technology Pvt. Ltd.'

extra_css: 
  - assets/style.css

extra:
  social:
    - type: 'github'
      link: 'https://github.com/zerodhatech/dotnetkiteconnect'

markdown_extensions:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true